services:
  sep-db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sep
    ports:
      - "3334:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  sep-backend:
    image: sep-backend
    ports:
      - "5148:8080"
      - "7006:8081"
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  pgdata:
